### ISSUE TITLE
App is Crashing On Open. 

### ISSUE THREAD

**Issue by sw0rdfish** [Dimillian/ACHNBrowserUI#132]
iOS 13.3.1
Unsure of AC Helper version. 

I checked it last night and had the check boxes for the villagers ( was stars the day before ) then today my only option was to delete and re-install. Is there any logs I can pull? 

Sucks cuz all my data is gone :(

**Comment by grantjbutler** [comment]
I'm also experiencing a crash on launch. I've attached a crash log in hopes that it helps figure out the issue. 

[AC Helper-2020-05-13-190632.log](https://github.com/Dimillian/ACHNBrowserUI/files/4625152/AC.Helper-2020-05-13-190632.log)

**Comment by TheVaan** [comment]
@grantjbutler the bug was fixed in 1.2.3, it was released ~10 hours ago. Maybe you have to force refresh App Stores available updates. You now should get 1.2.4

@sw0rdfish I‘m really sorry that you lost your data! I think your problem was v1.2.2 of AC Helper. It was shipped with a localization bug that did not occur on the devs device due to different localization settings. The App Store is a little bit broken since iOS 12 and you have to force update the list of available updates to find them. I have to add, that we have noticed a display bug in iOS 13.3.1 and AC Helper. iOS 13.4.1 fixes this issue because it was a bug in swift. If you don’t have to stay on 13.3.1, please update iOS.

**Comment by Dimillian** [comment]
@sw0rdfish @grantjbutler Yep, sorry about the issue, could you both confirm the latest App Store update solve the issue? Thanks!

**Comment by jonnyklemmer** [comment]
I was having the same issue and can confirm 1.2.4 update fixed it. @TheVaan @Dimillian

**Comment by sw0rdfish** [comment]
Sorry yeah it was fine after I reinstalled... it's annoying that I can't easily update apps anymore.. I tried everything to find an update for it, but it didn't work.  Glad to hear the problem is licked! No worries on the data, it's juts a critters list.  Is it possible to backup the data for this app on iCloud or does that complicate things?  I wish I was up to date with my programming so I could help rather than just making suggestions.  I do plan to dive in a bit this weekend to see how much I can pickup.

**Comment by Dimillian** [comment]
Next update is doing just that :)
![image](https://user-images.githubusercontent.com/535509/81978144-6629d880-962b-11ea-99c7-da79d4e87418.png)

**Comment by sw0rdfish** [comment]
You guys are damn wizards! I love it.  
How does Apple deal with automatically storing data there? Or is that not an option?  My concern is probably unnecessary but this may not be an option someone thinks to do on a regular basis... so they may do it once after the first import... but then going forward, they could lose weeks of data if it crashed on them again or they lost their phones.  Thoughts?

**Comment by TheVaan** [comment]
We already discussed iCloud integration. It’s a thing we have in mind, but it’s complicated in an open source project. There is possible a way and it will be on our watch list. That’s not a promise. I would love this feature, too - in my case for multi device using.

**Comment by Dimillian** [comment]
Basically we can’t do iCloud sync because of the project setup with open source for now. So this will let you export the file to wherever you want (even to iCloud folder). And so you can import it to any devices. Or even share it with friends so they can import it. ![image](https://user-images.githubusercontent.com/535509/81980553-1cdb8800-962f-11ea-91bb-77dd1c984832.png)

**Comment by sw0rdfish** [comment]
That makes sense. Thanks for taking the time to explain. Cheers!
