### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by izayl** [Dimillian/ACHNBrowserUI#43]
Env
```
macOS: 10.15.3 (19D76)
XCode Version 11.2.1 (11B500)
```
![image](https://user-images.githubusercontent.com/10740043/79944500-4117cf00-849e-11ea-8b19-d98e2af7026f.png)

**Comment by renaudjenny** [comment]
Could you try to go to File -> Swift Packages -> Update to Latest Package Versions

It happens to me sometimes when I just checkout a project, open with Xcode and press the build button too quickly :D

![image](https://user-images.githubusercontent.com/2297556/79945964-ec0c9680-8466-11ea-87ef-c291a1fa72bc.png)

Also, I use Xcode 11.4.1. But I don't think it's related with your issue. Tell me if that fixes the bug, otherwise I will have another look.

**Comment by Dimillian** [comment]
Also I think you need Xcode 11.4 / 11.4.1

**Comment by bigrck64** [comment]
Hey guys, I also can not build the project ! Maybe you can help :)
- macOS Mojave 10.14.6
- xCode 11.3.1

1/ git clone --recursive git://github.com/Dimillian/ACHNBrowserUI.git
2/ open ACHNBrowserUI.xcodeproj
3/ wait for Swift Package Dependencies to update
4/ force File > Swift Packages > Update to Latest Package Versions (just to be sure)
5/ change Signing & Capabilities to my dev Provisioning Profile & Bundle Identifier
6/ I got the following Package Loading Error :
![image](https://user-images.githubusercontent.com/9383270/79948759-c1c1d580-8474-11ea-81a9-0a6904db599a.png)

**Comment by Dimillian** [comment]
Really weird. Tried relaunching Xcode?

**Comment by Dimillian** [comment]
Maybe try with last commit. I've locked ACNHEvents version.

**Comment by bigrck64** [comment]
Hey Dimillian, thanks for the quick reply.
With fixed version of "1.1.0" I still have the same problem.
It's weird, it's like xcode internal git is just failing to find the correct tag.
![image](https://user-images.githubusercontent.com/9383270/79955517-339f1c80-847f-11ea-974a-fe3d24b2defd.png)

Maybe it's because I updated my git binary with brew ?
I'm currently downloading Xcode 11.4.1, maybe it will help

**Comment by bigrck64** [comment]
brew uninstall git > reboot > retry don't change anything.
I will report with xcode 11.4.1 when installed.

**Comment by bigrck64** [comment]
Well, I didn't know xcode 11.4.1 would need macOS 10.15.2 or later :(
![image](https://user-images.githubusercontent.com/9383270/79960367-9b586600-8485-11ea-9253-8ca69302e53e.png)

Dimillian, maybe your can build one .ipa and post it to release github page ?
I don't plan to update to 10.15 right now :)

**Comment by Dimillian** [comment]
You can join the testflight I guess then :) https://testflight.apple.com/join/AOM2G5Nx

**Comment by izayl** [comment]
@Dimillian Thanks, It works when I pull the latest commit `51fef70861`.

For anyone who has the same issue:

1. `git pull` to the latest commit SHA-1: 51fef70861

2. `open ACHNBrowserUI.xcodeproj `

3. Choose  File -> Swift Packages -> Update to Latest Package Versions

4. wait to all package resolved like this
![image](https://user-images.githubusercontent.com/10740043/79975214-345e9f80-84cd-11ea-9d8e-571b6b4f7928.png)

5. Successful build it 😄

**Comment by bigrck64** [comment]
Good new Izayl ! and you build it successfully with Xcode 11.2.1 !
Well, there must be a problem somewhere with macOS 10.14 vs 10.15 :(

Thanks for the testflight link Dimillian, I will use this :+1:

**Comment by ericlewis** [comment]
We should probably not commit `package.resolved` since it causes this problem. If it doesn't exist then Xcode will automatically generate it upon open. Will add to gitignore.
