### ISSUE TITLE
Remove reliance on private API for ACNH Google Sheet -> JSON conversion

### ISSUE THREAD

**Issue by gregcotten** [Dimillian/ACHNBrowserUI#70]

**Comment by Dimillian** [comment]
That would be totally awesome. Right now we're dumping the NookPlaza API once in a while. But now it changed quite a lot and will break all our models. NookPlaza already have the pipeline to do sheet -> clean JSON API. So maybe it would be a bit redundant.

**Comment by TheVaan** [comment]
I stumbled over [nookdata.com](https://nookdata.com/) [API](https://documenter.getpostman.com/view/11167637/SzfAy6Me?version=latest) while reading the translations sheet of ACNH data that is linked on NookPlaza. Could using the NookData API be an alternativ? With the API build into the app the users could get up to date data without updating the app it self.

Besides: If the dev adds multi language support (I send a tweet to him if there are any plans) via endpoint this could be really nice. (I had some trouble marking all fishes and bugs I allready owned because I had to compare images 😜)

**Comment by ericlewis** [comment]
@TheVaan we are attempting to avoid using live data (to some extent) because it’s nice to have it all offline. Eventually we hope to have a hybrid approach with local caching.

**Comment by TheVaan** [comment]
Yes, I also had a hybrid thing in mind. Force update database/cache after installation / update and a button in settings view to manually update cache. App could also be shipped with a default cache (up to date of release date).

**Comment by Dimillian** [comment]
Yeah this is definitely what we would go for. But for now we're not even up to date anymore because the data changed a lot and I need to clean it up for import in our current models.

**Comment by vknabel** [comment]
[ACNH API](http://acnhapi.com) also has undocumented endpoints returning a dict of all entries inside a category (e.g. [`GET /fish`](http://acnhapi.com/fish)).
Beside the differences in the data format: is there a reason not to use that for updating our data?

**Comment by Dimillian** [comment]
We already use a very recent dump of from NookPlaza and I’ve updated most of it today.  The main advantage is that it’s very homogenous dump so I can use Item for everything. I think the data issue Is almost solved. I’ll add an import / sync from within the app soon.
