### ISSUE TITLE
Custom lists of items

### ISSUE THREAD

**Issue by Dimillian** [Dimillian/ACHNBrowserUI#86]
The goal of the feature is to help people categorize their items in order to plan their house.

I see two ways of doing that. 
One a bit funky: 

* You see a sort of a AC house plan (a cut from top) with all the house rooms. And you can tap on them to add items and label them. You can also add items from item detail to labeled rooms. 

The other one more classic

* We have a Lists tab in the My Stuff tab and the user can create a new list with an icon and a title. And then we can search and add items from there or from item detail add to list. 

The first one is a bit more work but would be worth.

**Comment by ericlewis** [comment]
The first suggestion requires the user keep their house up to date in the app as they play the game, it is more friction- especially since that would probably be buried under a menu. 

The second suggestion is more traditional, but at least the user can just do something like “top floor” when they get one.

**Comment by Dimillian** [comment]
Actually it's done, just minor enchancements now :)
